# Generated by Django 6.0.2 on 2026-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_category_name_en_alter_category_name_kz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_kz',
            field=models.CharField(max_length=100, verbose_name='Category name in Kazakh'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Category name in Russian'),
        ),
    ]
