# Generated by Django 6.0.2 on 2026-02-12 14:12

import apps.users.validators
import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='User email address / Unique nickname', max_length=100, unique=True, validators=[apps.users.validators.check_domain_name], verbose_name='Email address')),
                ('first_name', models.CharField(max_length=50, verbose_name='User first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='User last name')),
                ('password', models.CharField(help_text='Hashed user password', max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, help_text='True if the user is active and has an access to request the data', verbose_name='Active status')),
                ('is_staff', models.BooleanField(default=False, help_text='True if user is part of company', verbose_name='Staff status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='User joined date')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='User avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
